<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="16349" started-at="2015-05-26T07:56:45Z" finished-at="2015-05-26T07:57:02Z">
    <groups>
      <group name="functest">
        <method signature="NewTest.testUINote1()[pri:0, instance:RegistrationTest.NewTest@1efea79]" name="testUINote1" class="RegistrationTest.NewTest"/>
      </group> <!-- functest -->
    </groups>
    <test name="Default test" duration-ms="16349" started-at="2015-05-26T07:56:45Z" finished-at="2015-05-26T07:57:02Z">
      <class name="RegistrationTest.NewTest">
        <test-method status="PASS" signature="setUpTest()[pri:0, instance:RegistrationTest.NewTest@1efea79]" name="setUpTest" is-config="true" duration-ms="6553" started-at="2015-05-26T10:56:45Z" finished-at="2015-05-26T10:56:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method status="FAIL" signature="testUINote1()[pri:0, instance:RegistrationTest.NewTest@1efea79]" name="testUINote1" duration-ms="7707" started-at="2015-05-26T10:56:52Z" finished-at="2015-05-26T10:57:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
 Something wrong in text expected [Use your mobile phone number to register this dev ice] but found [Use your mobile phone number to register this device]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
 Something wrong in text expected [Use your mobile phone number to register this dev ice] but found [Use your mobile phone number to register this device]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at RegistrationTest.NewTest.testUINote1(NewTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUINote1 -->
        <test-method status="PASS" signature="takeScreenShotOnFailure(org.testng.ITestResult)[pri:0, instance:RegistrationTest.NewTest@1efea79]" name="takeScreenShotOnFailure" is-config="true" duration-ms="605" started-at="2015-05-26T10:57:00Z" finished-at="2015-05-26T10:57:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testUINote1 status=FAILURE method=NewTest.testUINote1()[pri:0, instance:RegistrationTest.NewTest@1efea79] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- takeScreenShotOnFailure -->
        <test-method status="PASS" signature="shutDown()[pri:0, instance:RegistrationTest.NewTest@1efea79]" name="shutDown" is-config="true" duration-ms="1448" started-at="2015-05-26T10:57:00Z" finished-at="2015-05-26T10:57:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shutDown -->
      </class> <!-- RegistrationTest.NewTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
